"use client";
import { useEffect, useState } from "react";
import { Film, Upload, RefreshCw, ExternalLink, LogOut } from "lucide-react";
type Reel={url:string;title:string};
export default function Studio(){const [file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[uploading,setUploading]=useState(false),[msg,setMsg]=useState(''),[reels,setReels]=useState<Reel[]>([]);
 const load=()=>fetch('/api/reels').then(r=>r.json()).then(d=>setReels(d.reels||[])).catch(()=>setReels([]));useEffect(()=>{load()},[])
 const logout=async()=>{await fetch('/api/studio/logout',{method:'POST'});window.location.href='/studio/login'};
 const upload=async()=>{if(!file)return;setUploading(true);setMsg('');const fd=new FormData();fd.append('file',file);fd.append('title',title||file.name);const r=await fetch('/api/studio/upload-reel',{method:'POST',body:fd});const d=await r.json();setUploading(false);if(!r.ok){setMsg('Upload ยังไม่พร้อม: '+(d.error||'ตรวจสอบ Vercel Blob'));return}setMsg('อัปโหลดสำเร็จ');setFile(null);setTitle('');load()}
 return <div className="studio-light"><header className="studio-manager-head"><div><span>STUDIO</span><h1>Reel Manager</h1><p>อัปโหลดหรือเปลี่ยนไฟล์ Reel จากหน้านี้ แล้วหน้า Reels จะอ่านไฟล์จาก Vercel Blob อัตโนมัติ</p></div><button className="studio-logout" onClick={logout}><LogOut/> Logout</button></header>
 <section className="upload-card"><div className="upload-icon"><Film/></div><div><h2>Upload Reel Video</h2><p>แนะนำ 9:16 · MP4/H.264 · 1080×1920 หรือ 720×1280</p></div><label className="upload-drop"><input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><Upload/><b>{file?file.name:'เลือกไฟล์วิดีโอ'}</b><span>{file?`${(file.size/1024/1024).toFixed(1)} MB`:'Click to browse'}</span></label><input className="studio-title-input" placeholder="ชื่อ Reel" value={title} onChange={e=>setTitle(e.target.value)}/><button className="studio-upload-btn" disabled={!file||uploading} onClick={upload}>{uploading?'Uploading...':'Upload to Reels'}</button>{msg&&<p className="studio-msg">{msg}</p>}</section>
 <section className="studio-reel-list"><div className="studio-list-head"><h2>Reels on Vercel Blob</h2><button onClick={load}><RefreshCw/> Refresh</button></div>{reels.length===0?<div className="studio-empty">ยังไม่มีไฟล์บน Blob — ตอนนี้หน้า Reels จะใช้ตัวอย่าง 3 คลิปในเว็บแทน</div>:<div className="studio-reel-grid">{reels.map(r=><article key={r.url}><video src={r.url} muted playsInline/><div><b>{r.title}</b><a href={r.url} target="_blank"><ExternalLink/></a></div></article>)}</div>}</section>
 <aside className="blob-note"><b>ครั้งแรกบน Vercel:</b> ต้องสร้าง Vercel Blob Store ให้โปรเจกต์ 1 ครั้งก่อน การอัปโหลดจาก Studio จึงจะบันทึกออนไลน์ได้</aside></div>}
